import Cardx.ActionCard (ActionCard (..))
import Cardx.ActionKind (ActionKind (..))
import Cardx.Constant qualified as CC
import Cardx.FaceCard (FaceCard (..))
import Cardx.Model (Card (..), ColoredCard (..), ColoredKind (..))
import Cardx.Model qualified as CM
import Cardx.WildCard (WildCard (..))
import Cardx.WildKind (WildKind (..))
import Data.Vector qualified as V
import Relude
import Test.Hspec (describe, hspec, it, shouldBe)

main :: IO ()
main = hspec $ do
  describe "Model.hs" $ do
    it "makeWilds" $ do
      CM.makeWilds Wild `shouldBe` V.fromList [CWild (WildCard {kind = Wild, score = 50}), CWild (WildCard {kind = Wild, score = 50}), CWild (WildCard {kind = Wild, score = 50}), CWild (WildCard {kind = Wild, score = 50})]

    it "makeRange" $ do
      CM.makeRange 0 (\x -> RedCard (CKFaceCard (FaceCard x x))) (V.fromList [RedCard (CKActionCard (ActionCard {kind = Draw2, score = CC.actionScore})), RedCard (CKActionCard (ActionCard {kind = Skip, score = CC.actionScore}))])
        `shouldBe` V.fromList
          [ RedCard (CKActionCard (ActionCard {kind = Draw2, score = 20})),
            RedCard (CKActionCard (ActionCard {kind = Skip, score = 20})),
            RedCard (CKFaceCard (FaceCard {kind = 0, score = 0})),
            RedCard (CKFaceCard (FaceCard {kind = 1, score = 1})),
            RedCard (CKFaceCard (FaceCard {kind = 2, score = 2})),
            RedCard (CKFaceCard (FaceCard {kind = 3, score = 3})),
            RedCard (CKFaceCard (FaceCard {kind = 4, score = 4})),
            RedCard (CKFaceCard (FaceCard {kind = 5, score = 5})),
            RedCard (CKFaceCard (FaceCard {kind = 6, score = 6})),
            RedCard (CKFaceCard (FaceCard {kind = 7, score = 7})),
            RedCard (CKFaceCard (FaceCard {kind = 8, score = 8})),
            RedCard (CKFaceCard (FaceCard {kind = 9, score = 9}))
          ]
    it "makeColoredCardSet" $ do
      CM.makeColoredCardSet 0 GreenCard (V.fromList [ActionCard {kind = Skip, score = CC.actionScore}, ActionCard {kind = Skip, score = CC.actionScore}, ActionCard {kind = Draw2, score = CC.actionScore}])
        `shouldBe` V.fromList
          [ GreenCard (CKActionCard (ActionCard {kind = Skip, score = 20})),
            GreenCard (CKActionCard (ActionCard {kind = Skip, score = 20})),
            GreenCard (CKActionCard (ActionCard {kind = Draw2, score = 20})),
            GreenCard (CKFaceCard (FaceCard {kind = 0, score = 0})),
            GreenCard (CKFaceCard (FaceCard {kind = 1, score = 1})),
            GreenCard (CKFaceCard (FaceCard {kind = 2, score = 2})),
            GreenCard (CKFaceCard (FaceCard {kind = 3, score = 3})),
            GreenCard (CKFaceCard (FaceCard {kind = 4, score = 4})),
            GreenCard (CKFaceCard (FaceCard {kind = 5, score = 5})),
            GreenCard (CKFaceCard (FaceCard {kind = 6, score = 6})),
            GreenCard (CKFaceCard (FaceCard {kind = 7, score = 7})),
            GreenCard (CKFaceCard (FaceCard {kind = 8, score = 8})),
            GreenCard (CKFaceCard (FaceCard {kind = 9, score = 9}))
          ]

    it "makeColoreds" $ do
      CM.makeColoreds
        `shouldBe` V.fromList
          [ CColoredCard (RedCard (CKActionCard (ActionCard {kind = Skip, score = 20}))),
            CColoredCard (RedCard (CKActionCard (ActionCard {kind = Skip, score = 20}))),
            CColoredCard (RedCard (CKActionCard (ActionCard {kind = Draw2, score = 20}))),
            CColoredCard (RedCard (CKFaceCard (FaceCard {kind = 0, score = 0}))),
            CColoredCard (RedCard (CKFaceCard (FaceCard {kind = 1, score = 1}))),
            CColoredCard (RedCard (CKFaceCard (FaceCard {kind = 2, score = 2}))),
            CColoredCard (RedCard (CKFaceCard (FaceCard {kind = 3, score = 3}))),
            CColoredCard (RedCard (CKFaceCard (FaceCard {kind = 4, score = 4}))),
            CColoredCard (RedCard (CKFaceCard (FaceCard {kind = 5, score = 5}))),
            CColoredCard (RedCard (CKFaceCard (FaceCard {kind = 6, score = 6}))),
            CColoredCard (RedCard (CKFaceCard (FaceCard {kind = 7, score = 7}))),
            CColoredCard (RedCard (CKFaceCard (FaceCard {kind = 8, score = 8}))),
            CColoredCard (RedCard (CKFaceCard (FaceCard {kind = 9, score = 9}))),
            CColoredCard (YellowCard (CKActionCard (ActionCard {kind = Skip, score = 20}))),
            CColoredCard (YellowCard (CKActionCard (ActionCard {kind = Skip, score = 20}))),
            CColoredCard (YellowCard (CKActionCard (ActionCard {kind = Draw2, score = 20}))),
            CColoredCard (YellowCard (CKFaceCard (FaceCard {kind = 0, score = 0}))),
            CColoredCard (YellowCard (CKFaceCard (FaceCard {kind = 1, score = 1}))),
            CColoredCard (YellowCard (CKFaceCard (FaceCard {kind = 2, score = 2}))),
            CColoredCard (YellowCard (CKFaceCard (FaceCard {kind = 3, score = 3}))),
            CColoredCard (YellowCard (CKFaceCard (FaceCard {kind = 4, score = 4}))),
            CColoredCard (YellowCard (CKFaceCard (FaceCard {kind = 5, score = 5}))),
            CColoredCard (YellowCard (CKFaceCard (FaceCard {kind = 6, score = 6}))),
            CColoredCard (YellowCard (CKFaceCard (FaceCard {kind = 7, score = 7}))),
            CColoredCard (YellowCard (CKFaceCard (FaceCard {kind = 8, score = 8}))),
            CColoredCard (YellowCard (CKFaceCard (FaceCard {kind = 9, score = 9}))),
            CColoredCard (GreenCard (CKActionCard (ActionCard {kind = Skip, score = 20}))),
            CColoredCard (GreenCard (CKActionCard (ActionCard {kind = Skip, score = 20}))),
            CColoredCard (GreenCard (CKActionCard (ActionCard {kind = Draw2, score = 20}))),
            CColoredCard (GreenCard (CKFaceCard (FaceCard {kind = 0, score = 0}))),
            CColoredCard (GreenCard (CKFaceCard (FaceCard {kind = 1, score = 1}))),
            CColoredCard (GreenCard (CKFaceCard (FaceCard {kind = 2, score = 2}))),
            CColoredCard (GreenCard (CKFaceCard (FaceCard {kind = 3, score = 3}))),
            CColoredCard (GreenCard (CKFaceCard (FaceCard {kind = 4, score = 4}))),
            CColoredCard (GreenCard (CKFaceCard (FaceCard {kind = 5, score = 5}))),
            CColoredCard (GreenCard (CKFaceCard (FaceCard {kind = 6, score = 6}))),
            CColoredCard (GreenCard (CKFaceCard (FaceCard {kind = 7, score = 7}))),
            CColoredCard (GreenCard (CKFaceCard (FaceCard {kind = 8, score = 8}))),
            CColoredCard (GreenCard (CKFaceCard (FaceCard {kind = 9, score = 9}))),
            CColoredCard (BlueCard (CKActionCard (ActionCard {kind = Skip, score = 20}))),
            CColoredCard (BlueCard (CKActionCard (ActionCard {kind = Skip, score = 20}))),
            CColoredCard (BlueCard (CKActionCard (ActionCard {kind = Draw2, score = 20}))),
            CColoredCard (BlueCard (CKFaceCard (FaceCard {kind = 0, score = 0}))),
            CColoredCard (BlueCard (CKFaceCard (FaceCard {kind = 1, score = 1}))),
            CColoredCard (BlueCard (CKFaceCard (FaceCard {kind = 2, score = 2}))),
            CColoredCard (BlueCard (CKFaceCard (FaceCard {kind = 3, score = 3}))),
            CColoredCard (BlueCard (CKFaceCard (FaceCard {kind = 4, score = 4}))),
            CColoredCard (BlueCard (CKFaceCard (FaceCard {kind = 5, score = 5}))),
            CColoredCard (BlueCard (CKFaceCard (FaceCard {kind = 6, score = 6}))),
            CColoredCard (BlueCard (CKFaceCard (FaceCard {kind = 7, score = 7}))),
            CColoredCard (BlueCard (CKFaceCard (FaceCard {kind = 8, score = 8}))),
            CColoredCard (BlueCard (CKFaceCard (FaceCard {kind = 9, score = 9}))),
            CColoredCard (RedCard (CKActionCard (ActionCard {kind = Skip, score = 20}))),
            CColoredCard (RedCard (CKActionCard (ActionCard {kind = Skip, score = 20}))),
            CColoredCard (RedCard (CKActionCard (ActionCard {kind = Draw2, score = 20}))),
            CColoredCard (RedCard (CKFaceCard (FaceCard {kind = 1, score = 1}))),
            CColoredCard (RedCard (CKFaceCard (FaceCard {kind = 2, score = 2}))),
            CColoredCard (RedCard (CKFaceCard (FaceCard {kind = 3, score = 3}))),
            CColoredCard (RedCard (CKFaceCard (FaceCard {kind = 4, score = 4}))),
            CColoredCard (RedCard (CKFaceCard (FaceCard {kind = 5, score = 5}))),
            CColoredCard (RedCard (CKFaceCard (FaceCard {kind = 6, score = 6}))),
            CColoredCard (RedCard (CKFaceCard (FaceCard {kind = 7, score = 7}))),
            CColoredCard (RedCard (CKFaceCard (FaceCard {kind = 8, score = 8}))),
            CColoredCard (RedCard (CKFaceCard (FaceCard {kind = 9, score = 9}))),
            CColoredCard (YellowCard (CKActionCard (ActionCard {kind = Skip, score = 20}))),
            CColoredCard (YellowCard (CKActionCard (ActionCard {kind = Skip, score = 20}))),
            CColoredCard (YellowCard (CKActionCard (ActionCard {kind = Draw2, score = 20}))),
            CColoredCard (YellowCard (CKFaceCard (FaceCard {kind = 1, score = 1}))),
            CColoredCard (YellowCard (CKFaceCard (FaceCard {kind = 2, score = 2}))),
            CColoredCard (YellowCard (CKFaceCard (FaceCard {kind = 3, score = 3}))),
            CColoredCard (YellowCard (CKFaceCard (FaceCard {kind = 4, score = 4}))),
            CColoredCard (YellowCard (CKFaceCard (FaceCard {kind = 5, score = 5}))),
            CColoredCard (YellowCard (CKFaceCard (FaceCard {kind = 6, score = 6}))),
            CColoredCard (YellowCard (CKFaceCard (FaceCard {kind = 7, score = 7}))),
            CColoredCard (YellowCard (CKFaceCard (FaceCard {kind = 8, score = 8}))),
            CColoredCard (YellowCard (CKFaceCard (FaceCard {kind = 9, score = 9}))),
            CColoredCard (GreenCard (CKActionCard (ActionCard {kind = Skip, score = 20}))),
            CColoredCard (GreenCard (CKActionCard (ActionCard {kind = Skip, score = 20}))),
            CColoredCard (GreenCard (CKActionCard (ActionCard {kind = Draw2, score = 20}))),
            CColoredCard (GreenCard (CKFaceCard (FaceCard {kind = 1, score = 1}))),
            CColoredCard (GreenCard (CKFaceCard (FaceCard {kind = 2, score = 2}))),
            CColoredCard (GreenCard (CKFaceCard (FaceCard {kind = 3, score = 3}))),
            CColoredCard (GreenCard (CKFaceCard (FaceCard {kind = 4, score = 4}))),
            CColoredCard (GreenCard (CKFaceCard (FaceCard {kind = 5, score = 5}))),
            CColoredCard (GreenCard (CKFaceCard (FaceCard {kind = 6, score = 6}))),
            CColoredCard (GreenCard (CKFaceCard (FaceCard {kind = 7, score = 7}))),
            CColoredCard (GreenCard (CKFaceCard (FaceCard {kind = 8, score = 8}))),
            CColoredCard (GreenCard (CKFaceCard (FaceCard {kind = 9, score = 9}))),
            CColoredCard (BlueCard (CKActionCard (ActionCard {kind = Skip, score = 20}))),
            CColoredCard (BlueCard (CKActionCard (ActionCard {kind = Skip, score = 20}))),
            CColoredCard (BlueCard (CKActionCard (ActionCard {kind = Draw2, score = 20}))),
            CColoredCard (BlueCard (CKFaceCard (FaceCard {kind = 1, score = 1}))),
            CColoredCard (BlueCard (CKFaceCard (FaceCard {kind = 2, score = 2}))),
            CColoredCard (BlueCard (CKFaceCard (FaceCard {kind = 3, score = 3}))),
            CColoredCard (BlueCard (CKFaceCard (FaceCard {kind = 4, score = 4}))),
            CColoredCard (BlueCard (CKFaceCard (FaceCard {kind = 5, score = 5}))),
            CColoredCard (BlueCard (CKFaceCard (FaceCard {kind = 6, score = 6}))),
            CColoredCard (BlueCard (CKFaceCard (FaceCard {kind = 7, score = 7}))),
            CColoredCard (BlueCard (CKFaceCard (FaceCard {kind = 8, score = 8}))),
            CColoredCard (BlueCard (CKFaceCard (FaceCard {kind = 9, score = 9})))
          ]
    it "makeDeck" $ do
      CM.makeDeck
        `shouldBe` V.fromList
          [ CWild (WildCard {kind = Wild, score = 50}),
            CWild (WildCard {kind = Wild, score = 50}),
            CWild (WildCard {kind = Wild, score = 50}),
            CWild (WildCard {kind = Wild, score = 50}),
            CWild (WildCard {kind = WildDraw4, score = 50}),
            CWild (WildCard {kind = WildDraw4, score = 50}),
            CWild (WildCard {kind = WildDraw4, score = 50}),
            CWild (WildCard {kind = WildDraw4, score = 50}),
            CColoredCard (RedCard (CKActionCard (ActionCard {kind = Skip, score = 20}))),
            CColoredCard (RedCard (CKActionCard (ActionCard {kind = Skip, score = 20}))),
            CColoredCard (RedCard (CKActionCard (ActionCard {kind = Draw2, score = 20}))),
            CColoredCard (RedCard (CKFaceCard (FaceCard {kind = 0, score = 0}))),
            CColoredCard (RedCard (CKFaceCard (FaceCard {kind = 1, score = 1}))),
            CColoredCard (RedCard (CKFaceCard (FaceCard {kind = 2, score = 2}))),
            CColoredCard (RedCard (CKFaceCard (FaceCard {kind = 3, score = 3}))),
            CColoredCard (RedCard (CKFaceCard (FaceCard {kind = 4, score = 4}))),
            CColoredCard (RedCard (CKFaceCard (FaceCard {kind = 5, score = 5}))),
            CColoredCard (RedCard (CKFaceCard (FaceCard {kind = 6, score = 6}))),
            CColoredCard (RedCard (CKFaceCard (FaceCard {kind = 7, score = 7}))),
            CColoredCard (RedCard (CKFaceCard (FaceCard {kind = 8, score = 8}))),
            CColoredCard (RedCard (CKFaceCard (FaceCard {kind = 9, score = 9}))),
            CColoredCard (YellowCard (CKActionCard (ActionCard {kind = Skip, score = 20}))),
            CColoredCard (YellowCard (CKActionCard (ActionCard {kind = Skip, score = 20}))),
            CColoredCard (YellowCard (CKActionCard (ActionCard {kind = Draw2, score = 20}))),
            CColoredCard (YellowCard (CKFaceCard (FaceCard {kind = 0, score = 0}))),
            CColoredCard (YellowCard (CKFaceCard (FaceCard {kind = 1, score = 1}))),
            CColoredCard (YellowCard (CKFaceCard (FaceCard {kind = 2, score = 2}))),
            CColoredCard (YellowCard (CKFaceCard (FaceCard {kind = 3, score = 3}))),
            CColoredCard (YellowCard (CKFaceCard (FaceCard {kind = 4, score = 4}))),
            CColoredCard (YellowCard (CKFaceCard (FaceCard {kind = 5, score = 5}))),
            CColoredCard (YellowCard (CKFaceCard (FaceCard {kind = 6, score = 6}))),
            CColoredCard (YellowCard (CKFaceCard (FaceCard {kind = 7, score = 7}))),
            CColoredCard (YellowCard (CKFaceCard (FaceCard {kind = 8, score = 8}))),
            CColoredCard (YellowCard (CKFaceCard (FaceCard {kind = 9, score = 9}))),
            CColoredCard (GreenCard (CKActionCard (ActionCard {kind = Skip, score = 20}))),
            CColoredCard (GreenCard (CKActionCard (ActionCard {kind = Skip, score = 20}))),
            CColoredCard (GreenCard (CKActionCard (ActionCard {kind = Draw2, score = 20}))),
            CColoredCard (GreenCard (CKFaceCard (FaceCard {kind = 0, score = 0}))),
            CColoredCard (GreenCard (CKFaceCard (FaceCard {kind = 1, score = 1}))),
            CColoredCard (GreenCard (CKFaceCard (FaceCard {kind = 2, score = 2}))),
            CColoredCard (GreenCard (CKFaceCard (FaceCard {kind = 3, score = 3}))),
            CColoredCard (GreenCard (CKFaceCard (FaceCard {kind = 4, score = 4}))),
            CColoredCard (GreenCard (CKFaceCard (FaceCard {kind = 5, score = 5}))),
            CColoredCard (GreenCard (CKFaceCard (FaceCard {kind = 6, score = 6}))),
            CColoredCard (GreenCard (CKFaceCard (FaceCard {kind = 7, score = 7}))),
            CColoredCard (GreenCard (CKFaceCard (FaceCard {kind = 8, score = 8}))),
            CColoredCard (GreenCard (CKFaceCard (FaceCard {kind = 9, score = 9}))),
            CColoredCard (BlueCard (CKActionCard (ActionCard {kind = Skip, score = 20}))),
            CColoredCard (BlueCard (CKActionCard (ActionCard {kind = Skip, score = 20}))),
            CColoredCard (BlueCard (CKActionCard (ActionCard {kind = Draw2, score = 20}))),
            CColoredCard (BlueCard (CKFaceCard (FaceCard {kind = 0, score = 0}))),
            CColoredCard (BlueCard (CKFaceCard (FaceCard {kind = 1, score = 1}))),
            CColoredCard (BlueCard (CKFaceCard (FaceCard {kind = 2, score = 2}))),
            CColoredCard (BlueCard (CKFaceCard (FaceCard {kind = 3, score = 3}))),
            CColoredCard (BlueCard (CKFaceCard (FaceCard {kind = 4, score = 4}))),
            CColoredCard (BlueCard (CKFaceCard (FaceCard {kind = 5, score = 5}))),
            CColoredCard (BlueCard (CKFaceCard (FaceCard {kind = 6, score = 6}))),
            CColoredCard (BlueCard (CKFaceCard (FaceCard {kind = 7, score = 7}))),
            CColoredCard (BlueCard (CKFaceCard (FaceCard {kind = 8, score = 8}))),
            CColoredCard (BlueCard (CKFaceCard (FaceCard {kind = 9, score = 9}))),
            CColoredCard (RedCard (CKActionCard (ActionCard {kind = Skip, score = 20}))),
            CColoredCard (RedCard (CKActionCard (ActionCard {kind = Skip, score = 20}))),
            CColoredCard (RedCard (CKActionCard (ActionCard {kind = Draw2, score = 20}))),
            CColoredCard (RedCard (CKFaceCard (FaceCard {kind = 1, score = 1}))),
            CColoredCard (RedCard (CKFaceCard (FaceCard {kind = 2, score = 2}))),
            CColoredCard (RedCard (CKFaceCard (FaceCard {kind = 3, score = 3}))),
            CColoredCard (RedCard (CKFaceCard (FaceCard {kind = 4, score = 4}))),
            CColoredCard (RedCard (CKFaceCard (FaceCard {kind = 5, score = 5}))),
            CColoredCard (RedCard (CKFaceCard (FaceCard {kind = 6, score = 6}))),
            CColoredCard (RedCard (CKFaceCard (FaceCard {kind = 7, score = 7}))),
            CColoredCard (RedCard (CKFaceCard (FaceCard {kind = 8, score = 8}))),
            CColoredCard (RedCard (CKFaceCard (FaceCard {kind = 9, score = 9}))),
            CColoredCard (YellowCard (CKActionCard (ActionCard {kind = Skip, score = 20}))),
            CColoredCard (YellowCard (CKActionCard (ActionCard {kind = Skip, score = 20}))),
            CColoredCard (YellowCard (CKActionCard (ActionCard {kind = Draw2, score = 20}))),
            CColoredCard (YellowCard (CKFaceCard (FaceCard {kind = 1, score = 1}))),
            CColoredCard (YellowCard (CKFaceCard (FaceCard {kind = 2, score = 2}))),
            CColoredCard (YellowCard (CKFaceCard (FaceCard {kind = 3, score = 3}))),
            CColoredCard (YellowCard (CKFaceCard (FaceCard {kind = 4, score = 4}))),
            CColoredCard (YellowCard (CKFaceCard (FaceCard {kind = 5, score = 5}))),
            CColoredCard (YellowCard (CKFaceCard (FaceCard {kind = 6, score = 6}))),
            CColoredCard (YellowCard (CKFaceCard (FaceCard {kind = 7, score = 7}))),
            CColoredCard (YellowCard (CKFaceCard (FaceCard {kind = 8, score = 8}))),
            CColoredCard (YellowCard (CKFaceCard (FaceCard {kind = 9, score = 9}))),
            CColoredCard (GreenCard (CKActionCard (ActionCard {kind = Skip, score = 20}))),
            CColoredCard (GreenCard (CKActionCard (ActionCard {kind = Skip, score = 20}))),
            CColoredCard (GreenCard (CKActionCard (ActionCard {kind = Draw2, score = 20}))),
            CColoredCard (GreenCard (CKFaceCard (FaceCard {kind = 1, score = 1}))),
            CColoredCard (GreenCard (CKFaceCard (FaceCard {kind = 2, score = 2}))),
            CColoredCard (GreenCard (CKFaceCard (FaceCard {kind = 3, score = 3}))),
            CColoredCard (GreenCard (CKFaceCard (FaceCard {kind = 4, score = 4}))),
            CColoredCard (GreenCard (CKFaceCard (FaceCard {kind = 5, score = 5}))),
            CColoredCard (GreenCard (CKFaceCard (FaceCard {kind = 6, score = 6}))),
            CColoredCard (GreenCard (CKFaceCard (FaceCard {kind = 7, score = 7}))),
            CColoredCard (GreenCard (CKFaceCard (FaceCard {kind = 8, score = 8}))),
            CColoredCard (GreenCard (CKFaceCard (FaceCard {kind = 9, score = 9}))),
            CColoredCard (BlueCard (CKActionCard (ActionCard {kind = Skip, score = 20}))),
            CColoredCard (BlueCard (CKActionCard (ActionCard {kind = Skip, score = 20}))),
            CColoredCard (BlueCard (CKActionCard (ActionCard {kind = Draw2, score = 20}))),
            CColoredCard (BlueCard (CKFaceCard (FaceCard {kind = 1, score = 1}))),
            CColoredCard (BlueCard (CKFaceCard (FaceCard {kind = 2, score = 2}))),
            CColoredCard (BlueCard (CKFaceCard (FaceCard {kind = 3, score = 3}))),
            CColoredCard (BlueCard (CKFaceCard (FaceCard {kind = 4, score = 4}))),
            CColoredCard (BlueCard (CKFaceCard (FaceCard {kind = 5, score = 5}))),
            CColoredCard (BlueCard (CKFaceCard (FaceCard {kind = 6, score = 6}))),
            CColoredCard (BlueCard (CKFaceCard (FaceCard {kind = 7, score = 7}))),
            CColoredCard (BlueCard (CKFaceCard (FaceCard {kind = 8, score = 8}))),
            CColoredCard (BlueCard (CKFaceCard (FaceCard {kind = 9, score = 9})))
          ]
