name: cardx
version: 0.1.0.0
github: "modotte/cardx"
license: BSD3
author: "modotte"
copyright: "2023 Modotte"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/modotte/cardx#readme>
default-extensions:
  - OverloadedStrings
  - OverloadedLabels
  - OverloadedRecordDot
  - DuplicateRecordFields
  - ImportQualifiedPost
  - NoFieldSelectors
  - NoImplicitPrelude
language: GHC2021

dependencies:
  - base >= 4.7 && < 5
  - relude
  - data-default-class
  - vector
  - optics
  - optics-core
  - monomer
  - text-show
  - random
  - random-shuffle

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  cardx-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - cardx

tests:
  cardx-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - cardx
      - hspec
